# general -------------------

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

unbind C-b
set -g prefix C-g
bind C-g send-prefix

set -g mouse on
set -s escape-time 0
set -g focus-events on
set -g history-limit 100000

bind r source-file ~/.tmux.conf \; display "Config reloaded!"


# status bar -------------------

set -g status-interval 3
set -g status-style "bg=#1a1b26 fg=#c0caf5"
set -g status-right "#{?client_prefix,#[bg=red] PREFIX ,}"


# session -------------------

bind C-c new-session
bind C-f command-prompt -p find-session 'switch-client -t %%'   # find session
bind BTab switch-client -l                                      # move to last session


# window -------------------
#
set -g base-index 1

unbind '"'
unbind %
bind "|" split-window -h -c "#{pane_current_path}"
bind "-" split-window -v -c "#{pane_current_path}"

bind X kill-window
bind c new-window -c "#{pane_current_path}"

bind -r C-h previous-window
bind -r C-l next-window
bind -r Tab last-window


# pane -------------------

setw -g pane-base-index 1

bind x kill-pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind > swap-pane -D         # swap current pane with the next one
bind < swap-pane -U         # swap current pane with the previous one

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5


# vi-mode -------------------

bind Enter copy-mode

setw -g mode-keys vi

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi H send -X start-of-line
bind -T copy-mode-vi L send -X end-of-line
bind -T copy-mode-vi Escape send -X cancel


# buffers -------------------

bind b list-buffers     # list paste buffers
bind p paste-buffer -p  # paste from the top paste buffer
bind P choose-buffer    # choose which buffer to paste from
